version: "3.4"
services:
  app:
    image: node:22
    volumes:
      - ./:/code
    working_dir: /code
    command: sh -c "test -d node_modules || npm install; npm run start"
    ports:
      - "8998:8998"
    tty: true